// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messaging.proto

package com.example.grpc;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string sender = 1;</code>
   */
  java.lang.String getSender();
  /**
   * <code>string sender = 1;</code>
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <code>string recipient = 2;</code>
   */
  java.lang.String getRecipient();
  /**
   * <code>string recipient = 2;</code>
   */
  com.google.protobuf.ByteString
      getRecipientBytes();

  /**
   * <code>string text = 3;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
